services:
  nginx:
    image: nginx
    restart: always
    ports: [ "8000:8000" ]
    volumes: [ "./nginx-server.conf:/etc/nginx/conf.d/default.conf:ro" ]

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "./backend/settings.docker.yaml:/code/settings.yaml:ro" # Read-only settings file
    depends_on:
      db:
        condition: service_started
    environment:
      TZ: "Europe/Moscow"
      FORWARDED_ALLOW_IPS: "*"

  db:
    # See more: https://registry.hub.docker.com/_/mongo
    image: "mongo:8.0"
    restart: always
    volumes:
      - "mongodb:/data/db"
      - "./backend/dump:/dump"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-mongoadmin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-secret}

  minio:
    # See more: https://registry.hub.docker.com/minio/minio
    image: "minio/minio:RELEASE.2024-05-10T01-41-38Z"
    restart: always
    volumes:
      - "minio:/data"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}

  bot:
    profiles: [ bot ]  # Optional
    build: ./bot
    restart: always
    environment:
      TZ: "Europe/Moscow"
      BOT_TOKEN: ${BOT_TOKEN:-123456}

volumes:
  mongodb:
  minio:
