/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsImport } from './routes/terms'
import { Route as SearchImport } from './routes/search'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as FeedbackImport } from './routes/feedback'
import { Route as DisciplinesImport } from './routes/disciplines'
import { Route as CalendarImport } from './routes/calendar'
import { Route as AboutImport } from './routes/about'
import { Route as ManageRouteImport } from './routes/manage/route'
import { Route as IndexImport } from './routes/index'
import { Route as ManageIndexImport } from './routes/manage/index'
import { Route as FederationsIndexImport } from './routes/federations/index'
import { Route as FederationsFederationIdImport } from './routes/federations/$federationId'
import { Route as EventsEventIdImport } from './routes/events/$eventId'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as ManageRegionRequestsImport } from './routes/manage/region/requests'
import { Route as ManageRegionProfileImport } from './routes/manage/region/profile'
import { Route as ManageRegionHomeImport } from './routes/manage/region/home'
import { Route as ManageRegionFeedbackImport } from './routes/manage/region/feedback'
import { Route as ManageAdminHomeImport } from './routes/manage/admin/home'
import { Route as ManageAdminFederationsImport } from './routes/manage/admin/federations'
import { Route as ManageAdminEventsImport } from './routes/manage/admin/events'
import { Route as ManageRegionEventsIndexImport } from './routes/manage/region/events/index'
import { Route as ManageRegionEventsSuggestImport } from './routes/manage/region/events/suggest'
import { Route as ManageRegionEventsIdImport } from './routes/manage/region/events/$id'

// Create/Update Routes

const TermsRoute = TermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRoute,
} as any)

const SearchRoute = SearchImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const FeedbackRoute = FeedbackImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRoute,
} as any)

const DisciplinesRoute = DisciplinesImport.update({
  id: '/disciplines',
  path: '/disciplines',
  getParentRoute: () => rootRoute,
} as any)

const CalendarRoute = CalendarImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const ManageRouteRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ManageIndexRoute = ManageIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRouteRoute,
} as any)

const FederationsIndexRoute = FederationsIndexImport.update({
  id: '/federations/',
  path: '/federations/',
  getParentRoute: () => rootRoute,
} as any)

const FederationsFederationIdRoute = FederationsFederationIdImport.update({
  id: '/federations/$federationId',
  path: '/federations/$federationId',
  getParentRoute: () => rootRoute,
} as any)

const EventsEventIdRoute = EventsEventIdImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const ManageRegionRequestsRoute = ManageRegionRequestsImport.update({
  id: '/region/requests',
  path: '/region/requests',
  getParentRoute: () => ManageRouteRoute,
} as any)

const ManageRegionProfileRoute = ManageRegionProfileImport.update({
  id: '/region/profile',
  path: '/region/profile',
  getParentRoute: () => ManageRouteRoute,
} as any)

const ManageRegionHomeRoute = ManageRegionHomeImport.update({
  id: '/region/home',
  path: '/region/home',
  getParentRoute: () => ManageRouteRoute,
} as any)

const ManageRegionFeedbackRoute = ManageRegionFeedbackImport.update({
  id: '/region/feedback',
  path: '/region/feedback',
  getParentRoute: () => ManageRouteRoute,
} as any)

const ManageAdminHomeRoute = ManageAdminHomeImport.update({
  id: '/admin/home',
  path: '/admin/home',
  getParentRoute: () => ManageRouteRoute,
} as any)

const ManageAdminFederationsRoute = ManageAdminFederationsImport.update({
  id: '/admin/federations',
  path: '/admin/federations',
  getParentRoute: () => ManageRouteRoute,
} as any)

const ManageAdminEventsRoute = ManageAdminEventsImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => ManageRouteRoute,
} as any)

const ManageRegionEventsIndexRoute = ManageRegionEventsIndexImport.update({
  id: '/region/events/',
  path: '/region/events/',
  getParentRoute: () => ManageRouteRoute,
} as any)

const ManageRegionEventsSuggestRoute = ManageRegionEventsSuggestImport.update({
  id: '/region/events/suggest',
  path: '/region/events/suggest',
  getParentRoute: () => ManageRouteRoute,
} as any)

const ManageRegionEventsIdRoute = ManageRegionEventsIdImport.update({
  id: '/region/events/$id',
  path: '/region/events/$id',
  getParentRoute: () => ManageRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarImport
      parentRoute: typeof rootRoute
    }
    '/disciplines': {
      id: '/disciplines'
      path: '/disciplines'
      fullPath: '/disciplines'
      preLoaderRoute: typeof DisciplinesImport
      parentRoute: typeof rootRoute
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdImport
      parentRoute: typeof rootRoute
    }
    '/federations/$federationId': {
      id: '/federations/$federationId'
      path: '/federations/$federationId'
      fullPath: '/federations/$federationId'
      preLoaderRoute: typeof FederationsFederationIdImport
      parentRoute: typeof rootRoute
    }
    '/federations/': {
      id: '/federations/'
      path: '/federations'
      fullPath: '/federations'
      preLoaderRoute: typeof FederationsIndexImport
      parentRoute: typeof rootRoute
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/admin/events': {
      id: '/manage/admin/events'
      path: '/admin/events'
      fullPath: '/manage/admin/events'
      preLoaderRoute: typeof ManageAdminEventsImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/admin/federations': {
      id: '/manage/admin/federations'
      path: '/admin/federations'
      fullPath: '/manage/admin/federations'
      preLoaderRoute: typeof ManageAdminFederationsImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/admin/home': {
      id: '/manage/admin/home'
      path: '/admin/home'
      fullPath: '/manage/admin/home'
      preLoaderRoute: typeof ManageAdminHomeImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/region/feedback': {
      id: '/manage/region/feedback'
      path: '/region/feedback'
      fullPath: '/manage/region/feedback'
      preLoaderRoute: typeof ManageRegionFeedbackImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/region/home': {
      id: '/manage/region/home'
      path: '/region/home'
      fullPath: '/manage/region/home'
      preLoaderRoute: typeof ManageRegionHomeImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/region/profile': {
      id: '/manage/region/profile'
      path: '/region/profile'
      fullPath: '/manage/region/profile'
      preLoaderRoute: typeof ManageRegionProfileImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/region/requests': {
      id: '/manage/region/requests'
      path: '/region/requests'
      fullPath: '/manage/region/requests'
      preLoaderRoute: typeof ManageRegionRequestsImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/region/events/$id': {
      id: '/manage/region/events/$id'
      path: '/region/events/$id'
      fullPath: '/manage/region/events/$id'
      preLoaderRoute: typeof ManageRegionEventsIdImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/region/events/suggest': {
      id: '/manage/region/events/suggest'
      path: '/region/events/suggest'
      fullPath: '/manage/region/events/suggest'
      preLoaderRoute: typeof ManageRegionEventsSuggestImport
      parentRoute: typeof ManageRouteImport
    }
    '/manage/region/events/': {
      id: '/manage/region/events/'
      path: '/region/events'
      fullPath: '/manage/region/events'
      preLoaderRoute: typeof ManageRegionEventsIndexImport
      parentRoute: typeof ManageRouteImport
    }
  }
}

// Create and export the route tree

interface ManageRouteRouteChildren {
  ManageIndexRoute: typeof ManageIndexRoute
  ManageAdminEventsRoute: typeof ManageAdminEventsRoute
  ManageAdminFederationsRoute: typeof ManageAdminFederationsRoute
  ManageAdminHomeRoute: typeof ManageAdminHomeRoute
  ManageRegionFeedbackRoute: typeof ManageRegionFeedbackRoute
  ManageRegionHomeRoute: typeof ManageRegionHomeRoute
  ManageRegionProfileRoute: typeof ManageRegionProfileRoute
  ManageRegionRequestsRoute: typeof ManageRegionRequestsRoute
  ManageRegionEventsIdRoute: typeof ManageRegionEventsIdRoute
  ManageRegionEventsSuggestRoute: typeof ManageRegionEventsSuggestRoute
  ManageRegionEventsIndexRoute: typeof ManageRegionEventsIndexRoute
}

const ManageRouteRouteChildren: ManageRouteRouteChildren = {
  ManageIndexRoute: ManageIndexRoute,
  ManageAdminEventsRoute: ManageAdminEventsRoute,
  ManageAdminFederationsRoute: ManageAdminFederationsRoute,
  ManageAdminHomeRoute: ManageAdminHomeRoute,
  ManageRegionFeedbackRoute: ManageRegionFeedbackRoute,
  ManageRegionHomeRoute: ManageRegionHomeRoute,
  ManageRegionProfileRoute: ManageRegionProfileRoute,
  ManageRegionRequestsRoute: ManageRegionRequestsRoute,
  ManageRegionEventsIdRoute: ManageRegionEventsIdRoute,
  ManageRegionEventsSuggestRoute: ManageRegionEventsSuggestRoute,
  ManageRegionEventsIndexRoute: ManageRegionEventsIndexRoute,
}

const ManageRouteRouteWithChildren = ManageRouteRoute._addFileChildren(
  ManageRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/disciplines': typeof DisciplinesRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/federations/$federationId': typeof FederationsFederationIdRoute
  '/federations': typeof FederationsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/admin/events': typeof ManageAdminEventsRoute
  '/manage/admin/federations': typeof ManageAdminFederationsRoute
  '/manage/admin/home': typeof ManageAdminHomeRoute
  '/manage/region/feedback': typeof ManageRegionFeedbackRoute
  '/manage/region/home': typeof ManageRegionHomeRoute
  '/manage/region/profile': typeof ManageRegionProfileRoute
  '/manage/region/requests': typeof ManageRegionRequestsRoute
  '/manage/region/events/$id': typeof ManageRegionEventsIdRoute
  '/manage/region/events/suggest': typeof ManageRegionEventsSuggestRoute
  '/manage/region/events': typeof ManageRegionEventsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/disciplines': typeof DisciplinesRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/federations/$federationId': typeof FederationsFederationIdRoute
  '/federations': typeof FederationsIndexRoute
  '/manage': typeof ManageIndexRoute
  '/manage/admin/events': typeof ManageAdminEventsRoute
  '/manage/admin/federations': typeof ManageAdminFederationsRoute
  '/manage/admin/home': typeof ManageAdminHomeRoute
  '/manage/region/feedback': typeof ManageRegionFeedbackRoute
  '/manage/region/home': typeof ManageRegionHomeRoute
  '/manage/region/profile': typeof ManageRegionProfileRoute
  '/manage/region/requests': typeof ManageRegionRequestsRoute
  '/manage/region/events/$id': typeof ManageRegionEventsIdRoute
  '/manage/region/events/suggest': typeof ManageRegionEventsSuggestRoute
  '/manage/region/events': typeof ManageRegionEventsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/manage': typeof ManageRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/calendar': typeof CalendarRoute
  '/disciplines': typeof DisciplinesRoute
  '/feedback': typeof FeedbackRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/auth/login': typeof AuthLoginRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/federations/$federationId': typeof FederationsFederationIdRoute
  '/federations/': typeof FederationsIndexRoute
  '/manage/': typeof ManageIndexRoute
  '/manage/admin/events': typeof ManageAdminEventsRoute
  '/manage/admin/federations': typeof ManageAdminFederationsRoute
  '/manage/admin/home': typeof ManageAdminHomeRoute
  '/manage/region/feedback': typeof ManageRegionFeedbackRoute
  '/manage/region/home': typeof ManageRegionHomeRoute
  '/manage/region/profile': typeof ManageRegionProfileRoute
  '/manage/region/requests': typeof ManageRegionRequestsRoute
  '/manage/region/events/$id': typeof ManageRegionEventsIdRoute
  '/manage/region/events/suggest': typeof ManageRegionEventsSuggestRoute
  '/manage/region/events/': typeof ManageRegionEventsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/manage'
    | '/about'
    | '/calendar'
    | '/disciplines'
    | '/feedback'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/auth/login'
    | '/events/$eventId'
    | '/federations/$federationId'
    | '/federations'
    | '/manage/'
    | '/manage/admin/events'
    | '/manage/admin/federations'
    | '/manage/admin/home'
    | '/manage/region/feedback'
    | '/manage/region/home'
    | '/manage/region/profile'
    | '/manage/region/requests'
    | '/manage/region/events/$id'
    | '/manage/region/events/suggest'
    | '/manage/region/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/calendar'
    | '/disciplines'
    | '/feedback'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/auth/login'
    | '/events/$eventId'
    | '/federations/$federationId'
    | '/federations'
    | '/manage'
    | '/manage/admin/events'
    | '/manage/admin/federations'
    | '/manage/admin/home'
    | '/manage/region/feedback'
    | '/manage/region/home'
    | '/manage/region/profile'
    | '/manage/region/requests'
    | '/manage/region/events/$id'
    | '/manage/region/events/suggest'
    | '/manage/region/events'
  id:
    | '__root__'
    | '/'
    | '/manage'
    | '/about'
    | '/calendar'
    | '/disciplines'
    | '/feedback'
    | '/privacy'
    | '/search'
    | '/terms'
    | '/auth/login'
    | '/events/$eventId'
    | '/federations/$federationId'
    | '/federations/'
    | '/manage/'
    | '/manage/admin/events'
    | '/manage/admin/federations'
    | '/manage/admin/home'
    | '/manage/region/feedback'
    | '/manage/region/home'
    | '/manage/region/profile'
    | '/manage/region/requests'
    | '/manage/region/events/$id'
    | '/manage/region/events/suggest'
    | '/manage/region/events/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageRouteRoute: typeof ManageRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CalendarRoute: typeof CalendarRoute
  DisciplinesRoute: typeof DisciplinesRoute
  FeedbackRoute: typeof FeedbackRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  FederationsFederationIdRoute: typeof FederationsFederationIdRoute
  FederationsIndexRoute: typeof FederationsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageRouteRoute: ManageRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CalendarRoute: CalendarRoute,
  DisciplinesRoute: DisciplinesRoute,
  FeedbackRoute: FeedbackRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  AuthLoginRoute: AuthLoginRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  FederationsFederationIdRoute: FederationsFederationIdRoute,
  FederationsIndexRoute: FederationsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/manage",
        "/about",
        "/calendar",
        "/disciplines",
        "/feedback",
        "/privacy",
        "/search",
        "/terms",
        "/auth/login",
        "/events/$eventId",
        "/federations/$federationId",
        "/federations/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/manage": {
      "filePath": "manage/route.tsx",
      "children": [
        "/manage/",
        "/manage/admin/events",
        "/manage/admin/federations",
        "/manage/admin/home",
        "/manage/region/feedback",
        "/manage/region/home",
        "/manage/region/profile",
        "/manage/region/requests",
        "/manage/region/events/$id",
        "/manage/region/events/suggest",
        "/manage/region/events/"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/calendar": {
      "filePath": "calendar.tsx"
    },
    "/disciplines": {
      "filePath": "disciplines.tsx"
    },
    "/feedback": {
      "filePath": "feedback.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/terms": {
      "filePath": "terms.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/events/$eventId": {
      "filePath": "events/$eventId.tsx"
    },
    "/federations/$federationId": {
      "filePath": "federations/$federationId.tsx"
    },
    "/federations/": {
      "filePath": "federations/index.tsx"
    },
    "/manage/": {
      "filePath": "manage/index.tsx",
      "parent": "/manage"
    },
    "/manage/admin/events": {
      "filePath": "manage/admin/events.tsx",
      "parent": "/manage"
    },
    "/manage/admin/federations": {
      "filePath": "manage/admin/federations.tsx",
      "parent": "/manage"
    },
    "/manage/admin/home": {
      "filePath": "manage/admin/home.tsx",
      "parent": "/manage"
    },
    "/manage/region/feedback": {
      "filePath": "manage/region/feedback.tsx",
      "parent": "/manage"
    },
    "/manage/region/home": {
      "filePath": "manage/region/home.tsx",
      "parent": "/manage"
    },
    "/manage/region/profile": {
      "filePath": "manage/region/profile.tsx",
      "parent": "/manage"
    },
    "/manage/region/requests": {
      "filePath": "manage/region/requests.tsx",
      "parent": "/manage"
    },
    "/manage/region/events/$id": {
      "filePath": "manage/region/events/$id.tsx",
      "parent": "/manage"
    },
    "/manage/region/events/suggest": {
      "filePath": "manage/region/events/suggest.tsx",
      "parent": "/manage"
    },
    "/manage/region/events/": {
      "filePath": "manage/region/events/index.tsx",
      "parent": "/manage"
    }
  }
}
ROUTE_MANIFEST_END */
